### ISSUE TITLE
Download doesn't work with relative urls

### ISSUE THREAD

**Issue by fcdev** [Loghiks/HLSDownloader#1]
Example:
https://www.saturnspeed8.org/DDL/ANIME/Naruto/055/480p.m3u8
In this playlist the segments are relative to the url so they're saved like:
```
#EXTINF:8.333333,
480p_000.ts
```
The code check if the line start with `"http"`, so it can't find the urls of the segments because of this.

**Comment by Loghiks** [comment]
Thanks for your feedback and improvement.
I just commit a fix, and now the relative url works fine !
[https://github.com/Loghiks/HLSDownloader/commit/59f2164c8274b8e56958fad43ce3df82937177ea](url)
